- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: restart phonebook
  service:
    name: phonebook
    state: restarted
